### ISSUE TITLE
[Feedback wanted] Return type for XREAD/XREADGROUP

### ISSUE THREAD

**Issue by uki00a** [denodrivers/redis#109]
We now adopt `Map` as the return type for XREAD and XREADGROUP.
But I also think there are advantages of adopting `Record` over `Map`.
If you have an opinion about this, please leave a comment :smiley:

See also: #86

**Comment by tumile** [comment]
I think a Map here is a little overkill... Record is lighter, and we are only use string keys. For iterating, I don't see why a `for..in` loop is not sufficient...

**Comment by uki00a** [comment]
My concern was that `Record` would not be able to preserve the order of fields in the stream entry (The order of properties returned by `for-in`, `Object.keys`, etc. was not guaranteed **until ES2020**).

However, I believe that [ES2020's 'for-in mechanics' proposal](https://github.com/tc39/proposal-for-in-order) will wipe off this concern :relieved: 

Therefore, I would like to adopt `Record` over `Map` :thinking:
