### ISSUE TITLE
Add JSDoc and missing commands

### ISSUE THREAD

**Issue by tumile** [denodrivers/redis#130]
I think the current state of `command.ts` can be improved. 
- We should add JSDoc to commands in RedisCommands. It could be useful to the user of the package.
- We are missing some commands, here are a few that I noticed
  - [ ] [client id](https://redis.io/commands/client-id), client kill, client list, client getname
  - [x] [lpos](https://redis.io/commands/lpos) (#171)
  - [x] [scan](https://redis.io/commands/scan) with TYPE option (added in 6.0) (#132)
  - [x] [replicaof](https://redis.io/commands/replicaof) with NO ONE option (#132)

**Comment by Terkwood** [comment]
Thanks for raising this. Although deno-doc is a bit rudimentary and doesn't currently JsDocs from our interface, one nice benefit of documenting the commands is that editors (at least VsCode) *can* expose the descriptions during the course of programming. So if anyone finds the time to improve our document coverage, it will definitely benefit some of our users.

https://deno.land/manual/tools/documentation_generator

> Currently, only exports in the style export <declaration> and export ... from ... are supported.

**Comment by uki00a** [comment]
Thank you for rasing this issue! :+1: I'll split this issue to make it easier to track progress! :wink:
