### ISSUE TITLE
Value type can be number

### ISSUE THREAD

**Issue by tumile** [denodrivers/redis#133]
For example https://github.com/denolib/deno-redis/blob/4ad600278d9c6aeccbbf624eb2593d895ebb9e1c/command.ts#L45 
should be 
```ts
 ping(message: string | number)
```
and in most places, key/value/element/member/argument can be both string and number.

**Comment by Terkwood** [comment]
I like this approach and believe it will be helpful for end users

**Comment by uki00a** [comment]
Support for the number type has been added in [v0.21.0](https://github.com/denodrivers/redis/releases/tag/v0.21.0)!

Thanks for the suggestion!
