### ISSUE TITLE
[Feedback wanted] Naming style

### ISSUE THREAD

**Issue by uki00a** [denodrivers/redis#136]
`deno-redis` currently uses the snake case style for methods and options.
However, in JavaScript, the camel case style seems to be more common.
If you have an opinion about this, please leave a comment :smiley:

**Comment by Terkwood** [comment]
I believe camelCase will provide the highest level of conformity to what's found in code bases online. That said, I think the most important thing is to make deno-redis consistent *with itself* (and we might already be there)

**Comment by Xirui** [comment]
I agree with @Terkwood. IMHO, consistency within a repo is good enough.

When the DenoLib community (which this repo is part of) has formalised a convention, we could then think about consistency cross repos.

**Comment by uki00a** [comment]
Since deno v1.7.1, the `deno lint` command recommends camel case style for variables/functions. I'd like to follow the deno lint style as much as possible, so I'll change naming to camel case style before v1 is released.
```shell
(camelcase) Identifier 'script_load' is not in camel case.
  script_load(script: string): Promise<Status>;
  ^^^^^^^^^^^
    at /home/uki00a/ghq/github.com/uki00a/redis/command.ts:990:2

    hint: Consider renaming `script_load` to `scriptLoad`
```

https://github.com/denodrivers/redis/pull/182/checks?check_run_id=1844485219
