### ISSUE TITLE
Moving: Under an Org

### ISSUE THREAD

**Issue by ebebbington** [denodrivers/redis#151]
Hey! :)  I've been speaking about deno drivers in the deno discord, and thought it might be a good idea to have a single org to hold all drivers (sql, mongo, redis etc), eg `denodrivers/postgres`, `.../mongo`, `.../sql`, `../sqlite`. I was curious on how you felt about moving your sqlite repo? The idea came about as the mongo driver for deno is unmaintained now (and a deno plugin so very unstable), and there's a few people saying 'oh i can't do it, it's too much work', so myself and @qu4k has put together an org and discord. Then it'd be amazing if all drivers were under a single roof.

Of course i wouldn't be the leader for the repo, we have teams within the org and channels within the discord to keep the division (so i have no role in redis which i should have really)

The end result is the deno community can develop stable drivers, and them being all under one roof

Let me know what you think :)

- [x] mongod
- [x] sqlite
- [x] postgres
- [x] mysql
- [ ] pgc4d (**no**)
- [ ] redis (TBC 😉 )

Thanks, Edward

**Comment by ebebbington** [comment]
FYI here are some links:
Org: https://github.com/denodrivers
Discord: https://discord.gg/FHtas8

**Comment by uki00a** [comment]
@ebebbington Hi! I'm one of maintainers of deno-redis. Personally, I think it would be a good idea :+1: However, the original author of deno-redis is @keroxp. So I'd like to hear his opinion as well :wink: 

@keroxp What do you think about moving deno-redis to other org?

**Comment by uki00a** [comment]
@keroxp What do you think about moving deno-redis to other org?

**Comment by ebebbington** [comment]
added `mysql` to the list

**Comment by uki00a** [comment]
@ebebbington I'm sorry for the late reply. I had a conversation with @keroxp. He is also in favor of moving the repository :+1: What should we do next?

**Comment by ebebbington** [comment]
@uki00a Cool! :D No problem for the late reply :) As of what to do next, all you'd need to do is move the repo under the denodrivers args. If @keroxp could join the discord channel (if that is cool with them) that would be great so i can add them to the redis team in Discord. Plus, it'll give a platform for users to chat

I will invite both of you to the org right now, and set up the `redis` team, discord channels and invite you, just to sort out all the permissions and stuff :)

**Comment by uki00a** [comment]
I've transferred `deno-redis` to `denodrivers` organization!

**Comment by ebebbington** [comment]
Woop woop! I'll close this 'issue' then :) The team and channels and have been properly setup now :)
