### ISSUE TITLE
bundle error

### ISSUE THREAD

**Issue by transtone** [denodrivers/redis#179]
`test.js`:
```js
import { connect } from "https://deno.land/x/redis/mod.ts";

const redis = await connect({
  hostname: "127.0.0.1",
  port: 6379,
});
const ok = await redis.set("hoge", "fuga");
const fuga = await redis.get("hoge");

console.log(ok, fuga)
```

use bundle command: ` deno bundle test.js --unstable test.bundle.js`

then run `deno run -A test.bundle.js`

got error:
```sh
error: Uncaught ReferenceError: connect is not defined
const redis = await connect(redis_config);
              ^
```

**Comment by uki00a** [comment]
@transtone Thank you for opening the issue!
What version of Deno are you using? I couldn't reproduce this issue with Deno v1.6.3 and v1.7.0... :thinking:

**Comment by transtone** [comment]
It with Deno v1.6.3 in ubuntu 2004.
