### ISSUE TITLE
pipeline.hgetall issue

### ISSUE THREAD

**Issue by akhimchak** [denodrivers/redis#223]
```
const pl = redis.pipeline();
pl.hgetall('foo:0');
pl.hgetall('foo:1');
const result = await pl.flush();

console.log(result);
// => [ ArrayReply {}, ArrayReply {} ]

```
But hashes are exists. 
Other command I didn't test.

**Comment by uki00a** [comment]
Hi @akhimchak, thank you for opening this issue! I'd like to know about the behaviour you expect.

In that case, the `flush()` method currently returns results in the form of `Array<ArrayReply>`. In contrast, your expected result is `Array<Array<string>>`. Am I understanding your intension correctly? :thinking:

**Comment by akhimchak** [comment]
Hi @uki00a, I mean data exists in the redis, but when executed listed commands hashes are empty.
v0.19.0 works' fine in that case.

**Comment by uki00a** [comment]
I've opened the PR #227 to fix this issue. Could you please review it when you have time? :slightly_smiling_face:
