### ISSUE TITLE
Allow authenticating with the `connect` function

### ISSUE THREAD

**Issue by lilnasy** [denodrivers/redis#281]
The connect function only accepts hostname and port. Authentication has to be manually done as another step. This may mean you need to write some conditional logic when working on a production environment with authentication and a dev environment without.

I propose we work this conditional logic into the connect function, with the following API.

```ts
connect({
    hostname: "us-west.redislabs.com",
    port    : 14761,
    username: "default",
    password: "INsjxl"
})
```

This API is consistent with the URL interface, which means we can easily reference an environment variable like this example,
```ts
connect( new URL( Deno.env.get("REDISURL") )
```

where `REDISURL` can be `redis://default:INsjxl@us-west.redislabs.com:14761/` in which case, authentication is attempted or `redis://localhost:6379`in which case, no command is automatically run.

I can open a PR if you give the go ahead.

**Comment by uki00a** [comment]
@lilnasy I' m sorry for the late reply

> The connect function only accepts hostname and port. Authentication has to be manually done as another step. This may mean you need to write some conditional logic when working on a production environment with authentication and a dev environment without.

In that case, you can use the `parseURL()` function as follows:

```ts
import { connect, parseURL } from "https://deno.land/x/redis@v0.25.0/mod.ts";

const redis = await connect(parseURL(Deno.env.get("REDISURL")!));
```
