### ISSUE TITLE
Unable to connect to Redis with correct credentials

### ISSUE THREAD

**Issue by iuioiua** [denodrivers/redis#300]
I'm attempting to use a newly created Redis user. However, I'm getting the following error:
```bash
error: Uncaught (in promise) Error: -WRONGPASS invalid username-password pair

    throw new ErrorReplyError(line);
          ^
    at tryParseErrorReply (https://deno.land/x/redis@v0.25.4/protocol/reply.ts:205:11)
    at readReply (https://deno.land/x/redis@v0.25.4/protocol/reply.ts:55:7)
    at async RedisConnection.connectThunkified (https://deno.land/x/redis@v0.25.4/connection.ts:97:11)
    at async RedisConnection.connect (https://deno.land/x/redis@v0.25.4/connection.ts:126:5)
    at async connect (https://deno.land/x/redis@v0.25.4/redis.ts:2287:3)
    at async file://<location>
```
I'm essentially connecting to the following client via the following:
```ts
export const REDIS = await connect(parseURL(Deno.env.get("REDIS_URL")!));
```
When using my Redis default user, this code works fine. However, when using the new user, it doesn't. I know the `REDIS_URL` environmental variable is correct because I've used it to access Redis via `redis-cli -u <url>`.

Please let me know if there's any more information you need and thank you in advance.

**Comment by uki00a** [comment]
@isyouaint Thanks for the report! Could you tell us the format of the URL set in the `REDIS_URL` variable so we can investigate the cause in more detail?

**Comment by isyouaint** [comment]
> @isyouaint Thanks for the report! Could you tell us the format of the URL set in the `REDIS_URL` variable so we can investigate the cause in more detail?

As well, I tried connecting without using `parseURL` and got the same error. Format of the `REDIS_URL` variable is:

```
redis://<name>:<password>@<hostname>:<port>
```

**Comment by isyouaint** [comment]
@uki00a, I added a username parameter to `RedisConnection.authenticate` and was able to get this working. Reading [this](https://github.com/redis/redis-doc/blob/master/commands/auth.md) gave me the idea. Hopefully, this helps come to a solution.
Before:
```ts
private authenticate(password: string): Promise<RedisReply> {
  return sendCommand(this.writer, this.reader, "AUTH", password);
}
```

After:
```ts
private authenticate(username: string, password: string): Promise<RedisReply> {
  return sendCommand(this.writer, this.reader, "AUTH", username, password);
}
```

**Comment by Xirui** [comment]
@isyouaint I guess you are using Redis 6. 

The code in your Before block only works with Redis versions prior of 6.

**Comment by isyouaint** [comment]
Any issue with me adding this functionality in a PR?

**Comment by uki00a** [comment]
@isyouaint A PR will be welcome! :+1:

**Comment by scott-ling** [comment]
suggest you update `RedisConnectionOptions` to support `username?: string` and also update `authenticate' function to check for `username` and adjust redis command as needed for password/default auth `"AUTH", password` and if exists `"AUTH", username, password` 

not sure if this is being progresses, if not I am more than willing to make the carious changes as a PR let me know, as I am kind of making these changes to work with redislabs cloud right now anyway.

**Comment by scott-ling** [comment]
@uki00a all good, I will add a couple tests for the new situations

1. password passed no username passed
2. password and username passed

Will let ya know when its ready to roll, I should be able to complete this tonight once other work is done (I am on GMT)

Thanks for the quick turn-around, this was a breaking issue for me so assume its same for a few others.

-Scott

**Comment by iuioiua** [comment]
@scott-ling I haven’t yet started work on a PR, so I guess it’s yours 🤙🏾

**Comment by scott-ling** [comment]
Sorry for delay, PR made.
