### ISSUE TITLE
Subscribe / psubscribe hangs after calling sub.receive()

### ISSUE THREAD

**Issue by chromakode** [denodrivers/redis#390]
Hey, thanks very much for this project!

I've noticed that after a `RedisSubscription.receive()` loop has started, calls to `subscribe` or `psubscribe` never finish.

Here's the minimal repro:

```
const sub = await redis.subscribe(key)
sub.receive().next()
const sub2 = await redis.subscribe(key2)
// Never resolves
```

**Comment by uki00a** [comment]
Sorry for the late reply. I believe this problem has been resolved in [v0.32.1](https://github.com/denodrivers/redis/releases/tag/v0.32.1).
