### ISSUE TITLE
sendCommand api inconsistency

### ISSUE THREAD

**Issue by lifegit** [denodrivers/redis#393]
hi,
I really like your project, but I have a problem right now.

sendCommand in version 0.30.0:
`
  sendCommand(command: string, ...args: RedisValue[]): Promise<RedisReply>;
`

sendCommand in master:
`
  sendCommand(
    command: string,
    args?: RedisValue[],
    options?: SendCommandOptions,
  ): Promise<RedisReply>;
`

When can next version be released based on master? 

thinks you!

**Comment by uki00a** [comment]
[v0.31.0](https://github.com/denodrivers/redis/releases/tag/v0.31.0) has been released!

I plan to support RESP3. Because of this, there may still be breaking changes to the `sendCommand` API.
