### ISSUE TITLE
Broken types on v0.34.0

### ISSUE THREAD

**Issue by esroyo** [denodrivers/redis#460]
On version `v0.34.0` type hints seem to have broken for me:
![image](https://github.com/user-attachments/assets/65d5beee-9c6d-4895-9c39-927c957cedc3)

It is working fine for `v0.33.0` or `v0.32.4` (which I have been using for a while):
![image](https://github.com/user-attachments/assets/8c34f360-3b10-4f46-9b44-1138f47d1cad)

I'm testing it with Deno 2.0.0. Not sure if that is a problem in my system, It is a bit strange.

Let me know if more information is needed. Thanks so much :)

**Comment by uki00a** [comment]
@esroyo What happens when running `deno check` on a file that has type errors? :eyes:

```shell
$ deno check mod.ts
```

If `deno check` succeeds, `deno lsp` may not yet recognize `https://deno.land/x/redis@v0.34.0/mod.ts`. In that case, restarting `deno lsp` should resolve the problem.

**Comment by esroyo** [comment]
> @esroyo What happens when running `deno check` on a file that has type errors? 👀
> 
> ```shell
> $ deno check mod.ts
> ```
> 
> If `deno check` succeeds, `deno lsp` may not yet recognize `https://deno.land/x/redis@v0.34.0/mod.ts`. In that case, restarting `deno lsp` should resolve the problem.

Sorry for the faulty report @uki00a. It seems to work perfectly fine today :disappointed_relieved: 

I thought I had restarted everything yesterday. The fact that the typing information was working fine for all the versions with a fresh install, except for `v0.34.0` made me think the problem was not in the lsp.

Sorry for the misunderstanding, and thanks so much for the support and for this wonderful client :heart:
