### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by keroxp** [denodrivers/redis#78]
Deno@v1 has been released on 2020/05/13 and we adapted to them. But we have still many unsupported features (Cluster, Stream...) and Redis@v6 has also released recently. So we postpone v1 release of deno-redis for a while. 

We are very happy to have new contributor for theirs unsupported features. Please contribute our project!

- [x] Server API #35 
- [x] Stream API #36 
- [x] Cluster API #37 
- [ ] Redis@v6 support #105
- [x] Implement some missing commands #130
- [x] Stabilize APIs (#109)
- [x] get/set values from Uint8Array (#189)

**Comment by andreastoyota** [comment]
would be great to support redis@v6 before the first 3. I can already use the stream api using `redis.executor`, but i can't use RESP3

when we `await redis.executor.exec('HELLO', 3);` it fails with:
`error: Uncaught Error: Invalid state`

**Comment by halvardssm** [comment]
Hi @keroxp! Do you need any help with v6 support?

**Comment by Terkwood** [comment]
At least RESP3 support #80 and Cluster API #37 are most likely still up for grabs, as no one has reported starting work.

ACL and MODULE commands are complete. (#90)

Redis 6 also ships with STRALGO command, which we don't have a ticket to track. I'll open that up and link it here.

These are just my suggestions based on watching the status of the repo  - if the core maintainers contradict me, that's fine, please take your cue from them!
