### ISSUE TITLE
Do you or are you planning to support redis.client.xgroup?

### ISSUE THREAD

**Issue by reselbob** [denodrivers/redis#79]
I need a way to scale subscribers horizontally but make it so only one subscriber gets on message, not a whole bunch of subscribers getting that one message.

Lemme know, please. I am quite excited about Deno.

**Comment by reselbob** [comment]
I have a project coming up in which using Deno/Redis will be perfect. But, I need to make it scale. I need to make it so that when a client subscribes to a Redis topic it receives a unique message from the topic. If multiple instances are picking up the same message, that won't due. Maybe I can do this already using this module in the current version, but I am ignorant as to how to do this. If so, please educate me.

**Comment by keroxp** [comment]
@reselbob Do you talk about Streams API? If so, those apis haven't supported yet. I've never use those api. There are the plan but priority is still low.

**Comment by reselbob** [comment]
Yes, the Streams API

Here is a sample project I wrote to demonstrate the use of Groups to organize, produce, and consume stream emission from Redis in which a single, unique message is consumed per consume

https://github.com/reselbob/k8sdemos/tree/master/wordstream

**Comment by Terkwood** [comment]
Hi! #86 (implementation of Redis Streams API) will support this use case. I'll plan to add a test which demonstrates "one unique message per consumer"

**Comment by Terkwood** [comment]
There are a couple of tests covering this concern in the WIP pull request #86.

`test("unique message per consumer", async () => {`

and

`test("broadcast pattern, all groups read their own version of the stream", async () => {`
 
The broadcast pattern test shows how to accomplish the opposite of what you're asking (fan-out across all groups, useful for multiple services reading the same stream and processing it independently, etc), so it provides a nice contrast to the requested demo in this issue.

**Comment by Terkwood** [comment]
We should be able to close this issue once #86 is merged.  Cheers, and thanks again for bringing this up!
